# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GO_PROJECT: "go/excellent"

tasks:
  default:
    cmds:
      - task: audit
      - task: test
      - task: lint
      - task: fmt
      - task: run

  run:
    desc: Run excellent Go program
    dir: "{{.GO_PROJECT}}"
    cmds:
      - go run .

  fmt:
    desc: Format Go code
    dir: "{{.GO_PROJECT}}"
    cmds:
      - go fmt ./...

  test:
    desc: Test Go code
    dir: "{{.GO_PROJECT}}"
    cmds:
      - go test -v

  lint-go:
    desc: Lint Go code
    dir: "{{.GO_PROJECT}}"
    cmds:
      - go vet ./...
      - golangci-lint run

  audit-go:
    desc: Audit Go code
    dir: "{{.GO_PROJECT}}"
    cmds:
      - govulncheck ./...

  update-go:
    desc: Update Go dependencies
    dir: "{{.GO_PROJECT}}"
    cmds:
      - go get -u ./...
      - go mod tidy

  pinact-update:
    desc: Update GitHub Actions (both workflows and actions)
    cmds:
      - pinact run --update

  lint-workflows:
    desc: Lint GitHub Workflows
    cmds:
      - actionlint --verbose

  lint-workflows-docker:
    desc: Lint GitHub Workflows with Docker
    cmds:
      - docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest --verbose

  lint-actions:
    desc: Lint GitHub Workflows & Actions
    cmds:
      - find -name action.yml -o -name action.yaml | xargs action-validator -v

  lint:
    desc: Lint all
    cmds:
      - task: lint-go
      - task: lint-workflows
      - task: lint-actions

  audit:
    desc: Audit all
    cmds:
      - task: audit-go
